### ISSUE TITLE
CSS issues with DNN 9.X.X

### ISSUE THREAD

**Issue by Zeakk** [dnnconsulting/DnnC.MDesign#7]
It appears with the introduction of DNN 9.X.X that there are some CSS conflicts between MDB and Bootstrap...not really sure what the issues could be.

I also think that there needs to be better instruction on how to make global CSS changes...because not everything is dark background/white text.

Could be my lack of knowledge using DNN, but it just feels like this theme doesn't work well with the newest version.

**Comment by dnnconsulting** [comment]
Hi Zeakk,
I've just tested the MDesign theme on a Dnn9.0.1 install and I see no problems with the look of the theme as well as the functionality.

Could you be more specific with problems that you have.

1 thing you could check is the skin that you are using on pages. The 'Home' skin has a transparent menu bar which is by design so you can place a slide under the navbar. This makes it look like the content and menu are mixed up with each other. Try and change the skin to the 'Skin' skin.

Again, if you be more specific with the problems you are having I can try and correct them for you and others.

Regards,
Geoff.

**Comment by Zeakk** [comment]
Global CSS theme changes aren't really available...except for a few overrides.

MDB and Bootstrap have conflicting CSS styles, which is hard to decipher at times.

Once modules are set to a specific theme (panel-basic) for instance...the pages within the module don't necessarily take on the specific theme chosen...for instance DNN Blog module.

I can get around this with custom CSS work...but just thought it might be easier for end users to have the ability to do global CSS changes.

Also, MDB has updated to v4...any idea when that will be added to this theme?

Thanks,
Zeakk

**Comment by dnnconsulting** [comment]
Global changes are easy to do with the theme, I personally have created allot of sites using the theme as a base without problems.

There is an override.css file which you can use to override styles within the theme as well as creating new 'layout' sections which are found in the 'include' file.

As you know, this theme was created to make it easy for people for use and learn how to create themes for the Dnn platform, as was the case for the other 2 themes we created. This was the main goal of creating this theme for the community and has succeeded.

As for an upgrade to the MDesign theme, this will not be happening very soon. This is because of the license for the usage of MDBootstrap. For this version (3.1.1) we have a waver but I do not want to create an open source project that has restrictions which can be changed when ever they like.
